kind: Service
apiVersion: v1
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
spec:
  selector:
    app: PLACEHOLDER_SERVICE_NAME
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: PLACEHOLDER_NAMESPACE
  name: PLACEHOLDER_SERVICE_NAME
  labels:
    app: PLACEHOLDER_SERVICE_NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PLACEHOLDER_SERVICE_NAME
  template:
    metadata:
      labels:
        app: PLACEHOLDER_SERVICE_NAME
    spec:
      containers:
        - name: PLACEHOLDER_SERVICE_NAME
          image: PLACEHOLDER_DOCKER_IMAGE
          ports:
            - containerPort: 80
          lifecycle:
            postStart:
              exec:
                command: ["python","configure.py"]
      imagePullSecrets:
      - name: batman